# Player Placeholders
# {player-damage}
# {player-level}
# {player-health}
# {player-max-health}
# {player-gear-score}

# Weapon Placeholders
# {weapon-type}
# {weapon-rarity}
# {weapon-class}
# {weapon-required-level}
# {weapon-min-damage}
# {weapon-max-damage}
# {weapon-cooldown}
# {weapon-damage-per-seconds}
# {weapon-scroll-sockets}
# {weapon-gem-sockets}

format:
  prefix: '&7[&eSavageEquipment&7] &7'
  mob-names: '[{mob-level}] {mob-name} {mob-health}/{mob-max-health}'

events:
  damage: true
  join: true

features:
  cooldown: enabled

damage-indicator:
  name: '&c{player-damage}'
  client-side: true

exp-indicator:
  name: '&a{exp-amount}'
  client-side: true

formulas:
  exp: '{player-level} * 2.5 ^ 2 / 3.1415926535897932384626433832795 * 1.61803398875 * 100'
  exp-drop: '{mob-level} * 3.1415926535897932384626433832795 * 1.61803398875'
  player-damage: '{weapon-damage} + (1.25 * {player-str})'
  player-defense: '{weapon-damage} - (1.25 * {player-def})'
  mob-health: '{mob-level} * ({mob-health}^0.5)'
  mob-damage: '{mob-level} * {mob-damage} / 3.1415926535897932384626433832795'
  mob-defense: '{mob-level}^3.1415926535897932384626433832795 / {mob-health} / {mob-level}'

gear-score:
  multiplier:
    weapon:
      damage: 1.5
      cooldown: 0.75
    armor:
      protection: 1.5
      health: 1.5
      regen: 1.5

weapon:
  lore-amount: 15
  lore:
    - ' '
    - '&7Info:'
    - '&7» Type: &f{weapon-type}'
    - '&7» Rarity: &f{weapon-rarity}'
    - '&7» Required level: &f{weapon-required-level}'
    - ' '
    - '&7Weapon Stats:'
    - '&7» Damage: &f{weapon-min-damage}&7-&f{weapon-max-damage}'
    - '&7» Cooldown: &f{weapon-cooldown}'
    - ' '
    - '&7Gem Sockets:'
    - '&7» &f{weapon-gem-sockets}'
    - ' '

armor:
  lore-amount: 15
  lore:
    - ' '
    - '&7Info:'
    - '&7» Type: &f{armor-type}'
    - '&7» Rarity: &f{armor-rarity}'
    - '&7» Required level: &f{armor-required-level}'
    - ' '
    - '&7Weapon Stats:'
    - '&7» Protection: &f{armor-protection}'
    - '&7» Health: &f{armor-health}'
    - '&7» Regen: &f{armor-regen}'
    - ' '
    - '&7Gem Sockets:'
    - '&7» &f{armor-gem-sockets}'
    - ' '