name: SavageRPG
version: ${project.version}
main: net.prosavage.savagerpg.SavageRPG
authors: [KingAlterIV]
api-version: 1.14

commands:
   savagerpg:
    description: Main command for the plugin.
   giveitem:
    description: give item!