name: SavageEquipment
version: ${project.version}
main: net.prosavage.savageequipment.Main
authors: [KingAlterIV]
api-version: 1.13
commands:
  giveThing:
    description: Give things!
  romanToIntAndIntToRoman:
    description: Convert roman to a integer and back!