name: YaRPG
version: ${project.version}
main: net.prosavage.yarpg.YaRPG
api-version: 1.14
authors: [KingAlterIV]
<<<<<<< HEAD
description: An RPG core.
<<<<<<< HEAD
=======
=======
description: Yet Another RPG Core... but this one is customizable and free!
>>>>>>> 44737fc... Renamed things to YaRPG, added in new commands, fixed formatting, file count fixed, etc. / 12:00:11.62 - Sat 04/04/2020
depend:
  - ProtocolLib
softdepend:
  - WorldGuard
>>>>>>> 71fac37... Renamed things back, new & better files manager, more stuff fixed.

commands:
  weapon:
    description: The main weapon command of the plugin.
    aliases: weapons
  armor:
    description: The main armor command of the plugin.
    aliases: armors
  entity:
    description: The main basic entity command of the plugin.
    aliases: entities
  yarpg:
    description: The main command of the plugin.
    aliases: rpg