format:

  prefix: '&7[&fSavageEquipment&7] &7'

  # {mob-name} is required
  mob-names: '&7[&f{mob-level}&7] &f{mob-name} &c{mob-health}&7/&c{mob-max-health}&f'

  # {player-name} is required for nametags to function
  player-names: '&7[&f{player-level}&7] &f{player-name} &c{player-health-formatted}&7/&c{player-max-health-formatted}&f'

mob-spawn:
  center-x: 0.0
  center-z: 0.0
  block-difficulty-increase: 100.0
  mob-hp-increase: '{mob-health} * ({mob-distance} * {block-difficulty-increase})'

events:
  damage:
    player:
      enabled: true
    mobs:
      enabled: true
  join:
    enabled: true

  regen:
    enabled: true
    tick: 10

features:
  cooldown: enabled

damage-indicator:
  name: '&c{player-damage}'
  client-side: true

exp-indicator:
  name: '&f{exp-amount}'
  client-side: true

formulas:

  exp: '{player-level} * 2.5 * 2 ^ 3.1415926535897932384626433832795 ^ 1.61803398875 * 100'
  exp-drop: '{mob-max-health} / 3.1415926535897932384626433832795 / 1.61803398875'
  player-damage: '{player-recent-damage} + (1.25 * {player-str})'
  player-defense: '{damage} - ({damage} * (0.005 * {player-con}))'
  player-mana: '({player-int} * 1.25)'
  player-mana-regen: '({player-wis} * 0.05)'
  mob-health: '{mob-level} * ({mob-health}^0.5)'
  mob-damage: '{mob-level} * {mob-damage} / 3.1415926535897932384626433832795'
  mob-defense: '{damage} - ({damage} * ({mob-level}^3.1415926535897932384626433832795 / {mob-health} / {mob-level}))'

  player-damage-attribute: '(3.5 * {player-str})'
  player-health-attribute: '(25 * {player-str})'

  player-mana-attribute: '(2.5 * {player-int})'
  player-attribute-chance-attribute: '100 * (0.001 * {player-int})'

  player-defense-attribute: '(5 * {player-con})'
  player-constitution-health-attribute: '(10 * {player-con})'

  player-speed-attribute: '(0.01 * {player-dex})'
  player-evasion-attribute: '(0.01 * {player-dex})'

  player-liking-attribute: '(0.05 * {player-cha})'
  player-lower-price-attribute: '(0.01 * {player-cha})'

  player-mana-regeneration-attribute: '(0.5 * {player-wis})'
  player-ability-cooldown-attribute: '(0.09 * {player-wis})'

  player-loot-drop-attribute: '(0.01 * {player-luk})'

weapon:
  lore:
    - ' '
    - '&7Info:'
    - '&7» Type: &f{weapon-type}'
    - '&7» Rarity: &f{weapon-rarity}'
    - '&7» Required level: &f{weapon-required-level}'
    - ' '
    - '&7Weapon Stats:'
    - '&7» Damage: &f{weapon-min-damage}&7-&f{weapon-max-damage}'
    - ' '
    - '&7Gem Sockets'
    - '&7» &f{weapon-gem-sockets}'
    - ' '
    - '&7Weapon Ability'
    - '&7» &f{weapon-ability-name}'
    - '&7» Cooldown: &f{weapon-ability-cooldown}'
    - '&7» Cost: &f{weapon-ability-mana}'
    - '&7» &f{weapon-ability-description}'
    - ' '

armor:
  lore:
    - ' '
    - '&7Info:'
    - '&7» Type: &f{armor-type}'
    - '&7» Rarity: &f{armor-rarity}'
    - '&7» Required level: &f{armor-required-level}'
    - ' '
    - '&7Armor Stats:'
    - '&7» Protection: &f{armor-protection}'
    - '&7» Health: &f{armor-health}'
    - '&7» Regen: &f{armor-regen}'
    - ' '
    - '&7Gem Sockets'
    - '&7» &f{armor-gem-sockets}'
    - ' '

gui:
  attribute:
    Strength:
      material: IRON_SWORD
      name: '&cStrength'
      lore:
        - '&fIncreases your &cdamage'
        - '&falong with &chealth &fbonuses.'
        - ' '
        - '&fLevel: &c{player-str}'
        - '&fYou do &c{player-damage-equation} &fmore &cdamage'
        - '&fand gain &c{player-health-equation} &fmore &chealth&f.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10
    Intelligence:
      material: POTION
      name: '&bIntelligence'
      lore:
        - '&fIncreases your &bmana amount'
        - '&falong with a chance to obtain'
        - '&fanother attribute point when leveling up'
        - ' '
        - '&fLevel: &b{player-int}'
        - '&fYou get &b{player-mana-equation} &fmore mana'
        - '&fand have a &b{player-attribute-chance-equation} &fchance'
        - '&fof gaining another attribute'
        - '&apoint upon leveling up.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10
    Constitution:
      material: IRON_CHESTPLATE
      name: '&eConstitution'
      lore:
        - '&fIncreases your overall &edefense'
        - '&fand overall &ehealth&f.'
        - ' '
        - '&fLevel: &e{player-con}'
        - '&fYou get &e{player-defense-equation} &fmore &edefense'
        - '&fand gain &e{player-constitution-health-equation} &fmore &ehealth&f.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10
    Dexterity:
      material: LEATHER_BOOTS
      name: '&aDexterity'
      lore:
        - '&fIncreases your overall &aspeed'
        - '&fand overall &aevasion&f.'
        - ' '
        - '&fLevel: &a{player-dex}'
        - '&fYou get &a{player-speed-equation} &fmore &aspeed'
        - '&fand gain &a{player-evasion-equation} &fmore &aevasion&f.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10
    Charisma:
      material: PINK_WOOL
      name: '&dCharisma'
      lore:
        - '&fIncreases your overall &dliking from villagers'
        - '&fand overall &dlower price from villagers&f.'
        - ' '
        - '&fLevel: &d{player-cha}'
        - '&fVillagers like you &d{player-liking-equation} &fmore'
        - '&fand price went down by &d{player-lower-price-equation}&f.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10
    Wisdom:
      material: BLUE_WOOL
      name: '&4Wisdom'
      lore:
        - '&fIncreases your overall &dmana regeneration'
        - '&fand decreases overall &dability cooldown&f.'
        - ' '
        - '&fLevel: &b{player-wis}'
        - '&fVillagers like you &b{player-mana-regeneration-equation} &fmore'
        - '&fand price went down by &b{player-ability-cooldown-equation}&f.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10
    Luck:
      material: CONDUIT
      name: '&eLuck'
      lore:
        - '&fIncreases your overall &eloot drop from mobs'
        - ' '
        - '&fLevel: &e{player-luk}'
        - '&fLoot drop went up by &e{player-loot-drop-equation}&f.'
      warning-type: title
      title:
        title: 'Sorry, but...'
        subtitle: 'you don''t have enough attribute points'
        fadeIn: 10
        stay: 40
        fadeOut: 10


