name: SavageRPG
version: ${project.version}
main: net.prosavage.savagerpg.SavageRPG
api-version: 1.14
authors: [KingAlterIV]
depend:
  - ProtocolLib

commands:
  savagerpgdebug:
    description: The main command of the plugin.
  attributes:
    description: Attributes for the plugin!
